RepeatSoaker effect on DEGs detection
========================================================
```{r setup, echo=FALSE, include=FALSE, cache=FALSE}
# Set up the environment
library(knitr) 
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=T, dpi=300, out.width=700, echo=F)
options(replace.assign=TRUE, width=120)
set.seed(1)
HIDE=F # If true, mask any data labels
```

```{r loadLibraries, echo=FALSE, warning=FALSE, message=FALSE}
library("cummeRbund")
source("work_scripts//venn4.R")
source("work_scripts//venn5.R")
```

```{r loadData}
cuff_data <- lapply(list(all="data//cuffdiff-/", r75="data//cuffdiff-.75/", r50="data//cuffdiff-.50/", r25="data//cuffdiff-.25", r01="data//cuffdiff-.01/"), readCufflinks) # , r00="data//cuffdiff-.00", rebuild=TRUE
```

Overlap among DEGs identified in the non-soaked data ([[1]]) and RepeatSoaked data at 75%, 50, 25 and 1% thresholds.

```{r diffGeneIDs}
DEGcount <- function(cuff_data) {
  # As in the manual
  gene_diff_data <- diffData(genes(cuff_data),"CTRL","MUT",features=T)
  sig_gene_data <- subset(gene_diff_data, (significant == 'yes')) # Get significant only
  return(sig_gene_data)
}
# Get RepeatSoaker-specific results in a list
sig_genes <- lapply(cuff_data, DEGcount)

## 5-way venn diagram
# Get condition-specific lists of gene_id
sig_genes_names <- lapply(sig_genes, function(x) x$gene_id)
sapply(sig_genes_names, length)
names(sig_genes_names) <- names(cuff_data)
#do.call(plot_venn5, sig_genes_names)
plot_venn5(sig_genes_names[[1]], sig_genes_names[[2]], sig_genes_names[[3]], sig_genes_names[[4]], sig_genes_names[[5]])

```

We observe that soaking diminishes the number of differentially expressed genes. More rigorous soaking (less strict overlap threshold) also increases the number of genes not detected previously.

```{r venn4, eval=FALSE}
## 4-way venn diagram
# Get list of genes identified as DEGs in any condition
sig_genes_all <- unique(unlist(lapply(sig_genes, function(x) x$gene_id)))
# Create empty matrix to mark condition-specific DEGs
sig_genes_venn <- matrix(data=0, nrow=length(sig_genes_all), ncol=length(sig_genes))
rownames(sig_genes_venn) <- sig_genes_all
colnames(sig_genes_venn) <- names(cuff_data)
# Fill the matrix
for (i in 1:ncol(sig_genes_venn)) {
  sig_genes_venn[sig_genes[[i]]$gene_id[sig_genes[[i]]$log2_fold_change > 0], i] <- 1
  sig_genes_venn[sig_genes[[i]]$gene_id[sig_genes[[i]]$log2_fold_change < 0], i] <- -1
}
# Plot it as venn diagram
vennDiagram(sig_genes_venn[, 1:4], include="both")
```

